import { Profile, TaskDefinition, Expense, ShoppingItem, EquipmentItem, WoodInventory, RoomSnapshot, SosAlert } from '../types';

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'kamil',
    name: 'Kamil',
    colorHex: '#2563EB',
    bgColor: 'bg-blue-500',
    textColor: 'text-blue-700',
    avatar: '👨‍🌾',
    roleTitle: 'Gospodarz (Admin)',
    pin: '1482',
    isAdmin: true,
  },
  {
    id: 'ilona',
    name: 'Ilona',
    colorHex: '#D97706',
    bgColor: 'bg-amber-500',
    textColor: 'text-amber-700',
    avatar: '👩‍🌾',
    roleTitle: 'Żona / Organizatorka',
    pin: '2591',
    isAdmin: false,
  },
  {
    id: 'olivia',
    name: 'Olivia',
    colorHex: '#059669',
    bgColor: 'bg-emerald-500',
    textColor: 'text-emerald-700',
    avatar: '👧',
    roleTitle: 'Córka / Pomocniczka',
    pin: '3670',
    isAdmin: false,
  },
];

export const INITIAL_TASKS: TaskDefinition[] = [
  // === DREWNO & PIEC ===
  {
    id: 'task-wood-cut',
    name: 'Cięcie drewna do pieca',
    category: 'wood',
    frequency: 'weekly',
    seasonStart: 6,
    seasonEnd: 9,
    isCustom: false,
    room: 'Drewutnia',
    defaultOrder: 1,
    weatherSensitive: true,
    description: 'Naciąć i ułożyć drewno na zimę',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-wood-carry',
    name: 'Przynoszenie drewna do kotłowni',
    category: 'wood',
    frequency: 'daily',
    seasonStart: 10,
    seasonEnd: 3,
    isCustom: false,
    room: 'Kotłownia',
    defaultOrder: 2,
    description: 'Przynieść polana ze sztaua do kotłowni',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-stove-clean',
    name: 'Czyszczenie pieca',
    category: 'stove',
    frequency: 'weekly',
    seasonStart: 9,
    seasonEnd: 4,
    isCustom: false,
    room: 'Kotłownia',
    defaultOrder: 3,
    description: 'Wyczyścić ruszt, wybrać popiół',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === OGRÓD ===
  {
    id: 'task-mow-lawn',
    name: 'Koszenie trawy',
    category: 'garden',
    frequency: 'weekly',
    seasonStart: 4,
    seasonEnd: 10,
    isCustom: false,
    room: 'Ogród',
    defaultOrder: 4,
    weatherSensitive: true,
    description: 'Skosić trawnik wokół domu i altanki',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-garden-prep',
    name: 'Przygotowanie ogródka',
    category: 'garden',
    frequency: 'monthly',
    seasonStart: 3,
    seasonEnd: 5,
    isCustom: false,
    room: 'Ogród',
    defaultOrder: 5,
    weatherSensitive: true,
    description: 'Pielenie, nawożenie, przygotowanie grządek',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-water-plants',
    name: 'Podlewanie kwiatów',
    category: 'plants',
    frequency: 'twice_weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Ogród / Taras',
    defaultOrder: 6,
    description: 'Podlać rośliny doniczkowe i grządkowe',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === ZAKUPY ===
  {
    id: 'task-shopping',
    name: 'Zrobić zakupy',
    category: 'shopping',
    frequency: 'twice_weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 7,
    description: 'Zrobić zakupy spożywcze i domowe',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === SPRZĄTANIE — TWICE WEEKLY ===
  {
    id: 'task-vacuum-bedroom',
    name: 'Odkurzanie sypialni i przedpokoju',
    category: 'cleaning',
    frequency: 'twice_weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Sypialnia / Przedpokój',
    defaultOrder: 8,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-vacuum-olivia',
    name: 'Odkurzanie pokoju Olivii',
    category: 'cleaning',
    frequency: 'twice_weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Pokój Olivii',
    defaultOrder: 9,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-vacuum-stairs',
    name: 'Odkurzanie i mycie schodów',
    category: 'cleaning',
    frequency: 'twice_weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Klatka schodowa',
    defaultOrder: 10,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-kitchen-floor',
    name: 'Sprzątanie kuchni i mycie podłogi',
    category: 'cleaning',
    frequency: 'every_other_day',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Kuchnia',
    defaultOrder: 11,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-bathroom-floor',
    name: 'Mycie podłogi w łazience',
    category: 'cleaning',
    frequency: 'twice_weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Łazienka',
    defaultOrder: 12,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-dust-upstairs',
    name: 'Ścieranie kurzu na górze',
    category: 'cleaning',
    frequency: 'twice_weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Poddasze',
    defaultOrder: 13,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-clean-olivia',
    name: 'Sprzątanie pokoju Olivii',
    category: 'cleaning',
    frequency: 'twice_weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Pokój Olivii',
    defaultOrder: 14,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === SPRZĄTANIE — WEEKLY ===
  {
    id: 'task-mop-porch',
    name: 'Mycie podłogi na ganku',
    category: 'cleaning',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Ganek',
    defaultOrder: 15,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === SPRZĄTANIE — MONTHLY ===
  {
    id: 'task-clean-fridge',
    name: 'Sprzątanie lodówki',
    category: 'cleaning',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Kuchnia',
    defaultOrder: 16,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-change-bedding',
    name: 'Zmiana pościeli',
    category: 'laundry',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Sypialnia',
    defaultOrder: 17,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === CODZIENNE ===
  {
    id: 'task-dishes',
    name: 'Mycie naczyń',
    category: 'dishes',
    frequency: 'daily',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Kuchnia',
    defaultOrder: 18,
    description: 'Umyć naczynia po posiłku',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
];
export const INITIAL_SHOPPING_ITEMS: ShoppingItem[] = [];
export const INITIAL_EXPENSES: Expense[] = [];

export const INITIAL_WOOD_INVENTORY: WoodInventory = {
  estimatedM3: 0,
  totalCapacityM3: 15,
  lastCutDate: null,
  logsInBoilerRoom: 0,
  dailyBurnRateWinterM3: 0.1,
  updatedAt: new Date().toISOString(),
};

export const INITIAL_EQUIPMENT: EquipmentItem[] = [];
export const INITIAL_ROOM_SNAPSHOTS: RoomSnapshot[] = [];
export const INITIAL_SOS_ALERTS: SosAlert[] = [];
