import { Profile, TaskDefinition, Expense, ShoppingItem, EquipmentItem, WoodInventory, RoomSnapshot, SosAlert } from '../types';

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'kamil',
    name: 'Kamil',
    colorHex: '#2563EB',
    bgColor: 'bg-blue-500',
    textColor: 'text-blue-700',
    avatar: '👨‍🌾',
    roleTitle: 'Gospodarz (Admin)',
    pin: '1482',
    isAdmin: true,
  },
  {
    id: 'ilona',
    name: 'Ilona',
    colorHex: '#D97706',
    bgColor: 'bg-amber-500',
    textColor: 'text-amber-700',
    avatar: '👩‍🌾',
    roleTitle: 'Żona / Organizatorka',
    pin: '2591',
    isAdmin: false,
  },
  {
    id: 'olivia',
    name: 'Olivia',
    colorHex: '#059669',
    bgColor: 'bg-emerald-500',
    textColor: 'text-emerald-700',
    avatar: '👧',
    roleTitle: 'Córka / Pomocniczka',
    pin: '3670',
    isAdmin: false,
  },
];

export const INITIAL_TASKS: TaskDefinition[] = [
  // === DREWNO & PIEC (istniejące) ===
  {
    id: 'task-wood-cut',
    name: 'Cięcie drewna do pieca',
    category: 'wood',
    frequency: 'weekly',
    seasonStart: 6,
    seasonEnd: 9,
    isCustom: false,
    room: 'Drewutnia',
    defaultOrder: 1,
    weatherSensitive: true,
    description: 'Naciąć i ułożyć drewno na zimę',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-wood-carry',
    name: 'Przynoszenie drewna do kotłowni',
    category: 'wood',
    frequency: 'daily',
    seasonStart: 10,
    seasonEnd: 3,
    isCustom: false,
    room: 'Kotłownia',
    defaultOrder: 2,
    description: 'Przynieść polana ze sztaua do kotłowni',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-stove-clean',
    name: 'Czyszczenie pieca',
    category: 'stove',
    frequency: 'weekly',
    seasonStart: 9,
    seasonEnd: 4,
    isCustom: false,
    room: 'Kotłownia',
    defaultOrder: 3,
    description: 'Wyczyścić ruszt, wybrać popiół',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === OGRÓD (istniejące) ===
  {
    id: 'task-mow-lawn',
    name: 'Koszenie trawy',
    category: 'garden',
    frequency: 'weekly',
    seasonStart: 4,
    seasonEnd: 10,
    isCustom: false,
    room: 'Ogród',
    defaultOrder: 4,
    weatherSensitive: true,
    description: 'Skosić trawnik wokół domu i altanki',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-garden-prep',
    name: 'Przygotowanie ogródka',
    category: 'garden',
    frequency: 'monthly',
    seasonStart: 3,
    seasonEnd: 5,
    isCustom: false,
    room: 'Ogród',
    defaultOrder: 5,
    weatherSensitive: true,
    description: 'Pielenie, nawożenie, przygotowanie grządek',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-water-plants',
    name: 'Podlewanie kwiatów',
    category: 'plants',
    frequency: 'twice_weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Ogród / Taras',
    defaultOrder: 6,
    description: 'Podlać rośliny doniczkowe i grządkowe',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === ZAKUPY (istniejące) ===
  {
    id: 'task-shopping',
    name: 'Zrobić zakupy',
    category: 'shopping',
    frequency: 'twice_weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 7,
    description: 'Zrobić zakupy spożywcze i domowe',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === CODZIENNE — KUCHNIA I JEDZENIE ===
  {
    id: 'task-prepare-meals',
    name: 'Przygotowanie posiłków (śniadanie/obiad/kolacja)',
    category: 'cleaning',
    frequency: 'daily',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Kuchnia',
    defaultOrder: 8,
    description: 'Przygotować główny posiłek dnia',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-clear-table',
    name: 'Sprzątanie stołu po posiłku',
    category: 'cleaning',
    frequency: 'daily',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Kuchnia',
    defaultOrder: 9,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-load-dishwasher',
    name: 'Wkładanie naczyń do zmywarki',
    category: 'dishes',
    frequency: 'daily',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Kuchnia',
    defaultOrder: 10,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-unload-dishwasher',
    name: 'Opróżnianie zmywarki',
    category: 'dishes',
    frequency: 'daily',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Kuchnia',
    defaultOrder: 11,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-clean-countertops',
    name: 'Czyszczenie blatów kuchennych',
    category: 'cleaning',
    frequency: 'daily',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Kuchnia',
    defaultOrder: 12,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-check-fridge',
    name: 'Sprawdzenie lodówki i wyrzucenie zepsutych produktów',
    category: 'cleaning',
    frequency: 'daily',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Kuchnia',
    defaultOrder: 13,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-take-out-trash',
    name: 'Wynoszenie śmieci',
    category: 'cleaning',
    frequency: 'daily',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 14,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === CODZIENNE — PORZĄDEK ===
  {
    id: 'task-make-bed',
    name: 'Ścielenie łóżek',
    category: 'cleaning',
    frequency: 'daily',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Sypialnia',
    defaultOrder: 15,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-tidy-up',
    name: 'Odkładanie rzeczy na miejsce',
    category: 'cleaning',
    frequency: 'daily',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 16,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-ventilate',
    name: 'Wietrzenie mieszkania',
    category: 'cleaning',
    frequency: 'daily',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 17,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-quick-kitchen-clean',
    name: 'Szybkie sprzątanie kuchni',
    category: 'cleaning',
    frequency: 'daily',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Kuchnia',
    defaultOrder: 18,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-quick-bathroom-clean',
    name: 'Szybkie sprzątanie łazienki po użyciu',
    category: 'cleaning',
    frequency: 'daily',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Łazienka',
    defaultOrder: 19,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-fold-laundry',
    name: 'Odkładanie ubrań do szafy lub kosza na pranie',
    category: 'laundry',
    frequency: 'daily',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 20,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === CODZIENNE — DZIECI ===
  {
    id: 'task-kids-backpack',
    name: 'Przygotowanie plecaka i ubrań dla dziecka',
    category: 'cleaning',
    frequency: 'daily',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 21,
    description: 'Plecak, ubrania, przybory szkolne',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-kids-homework',
    name: 'Pomoc w lekcjach',
    category: 'cleaning',
    frequency: 'daily',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 22,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-kids-toys',
    name: 'Odkładanie zabawek',
    category: 'cleaning',
    frequency: 'daily',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Pokój Olivii',
    defaultOrder: 23,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-kids-bedtime',
    name: 'Przygotowanie dziecka do snu',
    category: 'cleaning',
    frequency: 'daily',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 24,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === SPRZĄTANIE — TWICE WEEKLY (istniejące) ===
  {
    id: 'task-vacuum-bedroom',
    name: 'Odkurzanie sypialni i przedpokoju',
    category: 'cleaning',
    frequency: 'twice_weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Sypialnia / Przedpokój',
    defaultOrder: 25,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-vacuum-olivia',
    name: 'Odkurzanie pokoju Olivii',
    category: 'cleaning',
    frequency: 'twice_weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Pokój Olivii',
    defaultOrder: 26,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-vacuum-stairs',
    name: 'Odkurzanie i mycie schodów',
    category: 'cleaning',
    frequency: 'twice_weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Klatka schodowa',
    defaultOrder: 27,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-kitchen-floor',
    name: 'Sprzątanie kuchni i mycie podłogi',
    category: 'cleaning',
    frequency: 'every_other_day',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Kuchnia',
    defaultOrder: 28,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-bathroom-floor',
    name: 'Mycie podłogi w łazience',
    category: 'cleaning',
    frequency: 'twice_weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Łazienka',
    defaultOrder: 29,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-dust-upstairs',
    name: 'Ścieranie kurzu na górze',
    category: 'cleaning',
    frequency: 'twice_weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Poddasze',
    defaultOrder: 30,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-clean-olivia',
    name: 'Sprzątanie pokoju Olivii',
    category: 'cleaning',
    frequency: 'twice_weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Pokój Olivii',
    defaultOrder: 31,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === TYGODNIOWE — ŁAZIENKA ===
  {
    id: 'task-clean-toilet',
    name: 'Mycie toalety',
    category: 'cleaning',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Łazienka',
    defaultOrder: 32,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-clean-sink',
    name: 'Czyszczenie umywalki i kranów',
    category: 'cleaning',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Łazienka',
    defaultOrder: 33,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-clean-mirror',
    name: 'Mycie lustra w łazience',
    category: 'cleaning',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Łazienka',
    defaultOrder: 34,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-clean-shower',
    name: 'Mycie wanny/prysznica i kabiny',
    category: 'cleaning',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Łazienka',
    defaultOrder: 35,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-clean-drains',
    name: 'Czyszczenie odpływów',
    category: 'cleaning',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Łazienka',
    defaultOrder: 36,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === TYGODNIOWE — SPRZĄTANIE ===
  {
    id: 'task-mop-porch',
    name: 'Mycie podłogi na ganku',
    category: 'cleaning',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Ganek',
    defaultOrder: 37,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-sort-trash',
    name: 'Segregacja odpadków i opróżnianie koszy',
    category: 'cleaning',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 38,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === TYGODNIOWE — PRANIE ===
  {
    id: 'task-laundry-sort',
    name: 'Segregacja i włączenie prania',
    category: 'laundry',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Łazienka',
    defaultOrder: 39,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-hang-laundry',
    name: 'Rozwieszanie i suszenie prania',
    category: 'laundry',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 40,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-fold-put-away',
    name: 'Składanie i odkładanie prania',
    category: 'laundry',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 41,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-iron',
    name: 'Prasowanie',
    category: 'laundry',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 42,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-wash-towels',
    name: 'Pranie ręczników',
    category: 'laundry',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Łazienka',
    defaultOrder: 43,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-replace-towels',
    name: 'Wymiana ręczników',
    category: 'cleaning',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Łazienka',
    defaultOrder: 44,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === MIESIĘCZNE — SPRZĄTANIE ===
  {
    id: 'task-clean-baseboards',
    name: 'Czyszczenie listew przypodłogowych',
    category: 'cleaning',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 45,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-clean-doors',
    name: 'Czyszczenie drzwi i klamek',
    category: 'cleaning',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 46,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-clean-windows-inside',
    name: 'Mycie okien wewnętrznych',
    category: 'cleaning',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 47,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-clean-radiators',
    name: 'Czyszczenie grzejników',
    category: 'cleaning',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 48,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-vacuum-sofa',
    name: 'Odkurzanie kanapy',
    category: 'cleaning',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Salon',
    defaultOrder: 49,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-organize-closets',
    name: 'Porządkowanie szaf i szuflad',
    category: 'cleaning',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 50,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === MIESIĘCZNE — KUCHNIA ===
  {
    id: 'task-clean-fridge',
    name: 'Sprzątanie lodówki',
    category: 'cleaning',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Kuchnia',
    defaultOrder: 51,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-clean-freezer',
    name: 'Czyszczenie zamrażarki',
    category: 'cleaning',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Kuchnia',
    defaultOrder: 52,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-clean-oven',
    name: 'Czyszczenie piekarnika',
    category: 'cleaning',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Kuchnia',
    defaultOrder: 53,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-clean-microwave',
    name: 'Czyszczenie mikrofalówki',
    category: 'cleaning',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Kuchnia',
    defaultOrder: 54,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-clean-hood',
    name: 'Czyszczenie okapu',
    category: 'cleaning',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Kuchnia',
    defaultOrder: 55,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-descale-appliances',
    name: 'Odkamienianie urządzeń (czajnik, pralka)',
    category: 'maintenance',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Kuchnia',
    defaultOrder: 56,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-change-bedding',
    name: 'Zmiana pościeli',
    category: 'laundry',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Sypialnia',
    defaultOrder: 57,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === MIESIĘCZNE — FINANSE I KONSERWACJA ===
  {
    id: 'task-review-expenses',
    name: 'Przegląd wydatków i kontrola budżetu',
    category: 'maintenance',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 58,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-check-bills',
    name: 'Sprawdzenie rachunków (prąd, gaz, woda, internet)',
    category: 'maintenance',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 59,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-check-subscriptions',
    name: 'Kontrola subskrypcji i abonamentów',
    category: 'maintenance',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 60,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-appliance-check',
    name: 'Kontrola sprzętu AGD i czyszczenie filtrów',
    category: 'maintenance',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 61,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-check-faucets',
    name: 'Kontrola kranów, odpływów, drzwi i okien',
    category: 'maintenance',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 62,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === SEZONOWE — WIOSNA ===
  {
    id: 'task-spring-windows',
    name: 'Mycie okien wiosenne',
    category: 'seasonal',
    frequency: 'monthly',
    seasonStart: 3,
    seasonEnd: 5,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 63,
    description: 'Mycie okien, parapetów, rolet/żaluzji',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-spring-closet',
    name: 'Przegląd garderoby — zamiana zimowych na wiosenne ubrania',
    category: 'seasonal',
    frequency: 'monthly',
    seasonStart: 3,
    seasonEnd: 4,
    isCustom: false,
    room: 'Sypialnia',
    defaultOrder: 64,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-spring-garden',
    name: 'Wiosenne porządki w ogrodzie i na balkonie',
    category: 'garden',
    frequency: 'monthly',
    seasonStart: 3,
    seasonEnd: 4,
    isCustom: false,
    room: 'Ogród',
    defaultOrder: 65,
    weatherSensitive: true,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === SEZONOWE — JESIEŃ ===
  {
    id: 'task-autumn-windows',
    name: 'Mycie okien jesiennych',
    category: 'seasonal',
    frequency: 'monthly',
    seasonStart: 9,
    seasonEnd: 10,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 66,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-autumn-gutters',
    name: 'Czyszczenie rynien',
    category: 'seasonal',
    frequency: 'monthly',
    seasonStart: 10,
    seasonEnd: 11,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 67,
    weatherSensitive: true,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-autumn-leaves',
    name: 'Grabienie liści',
    category: 'garden',
    frequency: 'weekly',
    seasonStart: 10,
    seasonEnd: 11,
    isCustom: false,
    room: 'Ogród',
    defaultOrder: 68,
    weatherSensitive: true,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-autumn-garden',
    name: 'Przygotowanie ogrodu do zimy',
    category: 'garden',
    frequency: 'monthly',
    seasonStart: 10,
    seasonEnd: 11,
    isCustom: false,
    room: 'Ogród',
    defaultOrder: 69,
    weatherSensitive: true,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-autumn-closet',
    name: 'Przegląd garderoby — zamiana letnich na zimowe ubrania',
    category: 'seasonal',
    frequency: 'monthly',
    seasonStart: 9,
    seasonEnd: 10,
    isCustom: false,
    room: 'Sypialnia',
    defaultOrder: 70,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-check-heating',
    name: 'Kontrola ogrzewania przed sezonem',
    category: 'stove',
    frequency: 'monthly',
    seasonStart: 9,
    seasonEnd: 10,
    isCustom: false,
    room: 'Kotłownia',
    defaultOrder: 71,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === SEZONOWE — ZIMA ===
  {
    id: 'task-check-heating-winter',
    name: 'Kontrola ogrzewania i temperatury w domu',
    category: 'stove',
    frequency: 'weekly',
    seasonStart: 11,
    seasonEnd: 3,
    isCustom: false,
    room: 'Kotłownia',
    defaultOrder: 72,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-snow-removal',
    name: 'Odśnieżanie',
    category: 'seasonal',
    frequency: 'daily',
    seasonStart: 11,
    seasonEnd: 3,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 73,
    weatherSensitive: true,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-check-windows-winter',
    name: 'Kontrola okien i drzwi (szczelność)',
    category: 'seasonal',
    frequency: 'monthly',
    seasonStart: 11,
    seasonEnd: 2,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 74,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === ZAKUPY — ROZBUDOWA ===
  {
    id: 'task-check-supplies',
    name: 'Sprawdzenie zapasów w szafkach i zamrażarce',
    category: 'shopping',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Kuchnia',
    defaultOrder: 75,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-shopping-list',
    name: 'Przygotowanie listy zakupów',
    category: 'shopping',
    frequency: 'twice_weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 76,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-unpack-shopping',
    name: 'Rozpakowanie i ułożenie zakupów',
    category: 'shopping',
    frequency: 'twice_weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Kuchnia',
    defaultOrder: 77,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === CODZIENNE — HIGIENA ===
  {
    id: 'task-refill-hygiene',
    name: 'Uzupełnianie środków higienicznych (papier, mydło)',
    category: 'cleaning',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Łazienka',
    defaultOrder: 78,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === ORGANIZACYJNE ===
  {
    id: 'task-meal-plan',
    name: 'Planowanie posiłków na tydzień',
    category: 'maintenance',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 79,
    description: 'Zaplanować śniadania, obiady, kolacje i przekąski',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-week-plan',
    name: 'Planowanie tygodnia (kalendarz, zadania, zakupy)',
    category: 'maintenance',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 80,
    description: 'Sprawdzić kalendarz, zaplanować sprzątanie, pranie, zakupy',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === OKAZJONALNE ===
  {
    id: 'task-holiday-plan',
    name: 'Planowanie świąt — lista zakupów, dekoracje, potrawy',
    category: 'occasional',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 81,
    description: 'Przygotowanie listy prezentów, potraw, dekoracji, sprzątanie przed świętami',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-birthday-prep',
    name: 'Przygotowanie urodzin / uroczystości',
    category: 'occasional',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 82,
    description: 'Zaplanować uroczystość, zaproszenia, jedzenie, dekoracje, sprzątanie',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-guest-prep',
    name: 'Przygotowanie domu na gości',
    category: 'occasional',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 83,
    description: 'Posprzątać, przygotować łazienkę, ręczniki, pościel, jedzenie',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-emergency-report',
    name: 'Zgłoszenie awarii / naprawa',
    category: 'occasional',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 84,
    description: 'Kontakt z administracją, hydraulikiem, elektrykiem, serwisem AGD',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-deep-clean-before-event',
    name: 'Generalne sprzątanie przed wydarzeniem',
    category: 'occasional',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 85,
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === ADMINISTRACYJNE ===
  {
    id: 'task-pay-bills',
    name: 'Opłacenie rachunków (prąd, gaz, woda, internet)',
    category: 'administrative',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 86,
    description: 'Sprawdzić terminy płatności i opłacić rachunki',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-check-insurance',
    name: 'Kontrola ubezpieczeń i terminów',
    category: 'administrative',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 87,
    description: 'Sprawdzić daty ważności ubezpieczeń, przeglądów, badań technicznych',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-sort-documents',
    name: 'Segregacja i archiwizacja dokumentów',
    category: 'administrative',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 88,
    description: 'Uporządkować rachunki, umowy, ważne dokumenty, wyrzucić niepotrzebne',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-backup-docs',
    name: 'Kopia zapasowa ważnych dokumentów',
    category: 'administrative',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 89,
    description: 'Skanowanie i archiwizacja ważnych dokumentów',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-government-affairs',
    name: 'Załatwianie spraw urzędowych',
    category: 'administrative',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 90,
    description: 'Wypełnianie formularzy, składanie dokumentów, umawianie wizyt, rozliczenia podatkowe',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-check-subscriptions-admin',
    name: 'Kontrola subskrypcji i abonamentów',
    category: 'administrative',
    frequency: 'monthly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 91,
    description: 'Przegląd wszystkich subskrypcji, rezygnacja z nieużywanych',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  // === ORGANIZACYJNE ===
  {
    id: 'task-meal-plan-weekly',
    name: 'Planowanie posiłków na tydzień',
    category: 'organizational',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 92,
    description: 'Zaplanować śniadania, obiady, kolacje, przekąski, listę zakupów',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-shopping-plan',
    name: 'Planowanie zakupów (lista, budżet, kategorie)',
    category: 'organizational',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 93,
    description: 'Sprawdzić zapasy, podzielić zakupy na kategorie, ustalić budżet',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-chores-plan',
    name: 'Podział obowiązków między domowników',
    category: 'organizational',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 94,
    description: 'Ustalić kto robi co w danym tygodniu, ustalić priorytety',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-week-review',
    name: 'Przegląd wykonanych zadań i przeniesienie niewykonanych',
    category: 'organizational',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 95,
    description: 'Sprawdzić co zostało zrobione, przenieść niewykonane na kolejny tydzień',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
  {
    id: 'task-family-plan',
    name: 'Planowanie czasu dla rodziny i odpoczynku',
    category: 'organizational',
    frequency: 'weekly',
    seasonStart: null,
    seasonEnd: null,
    isCustom: false,
    room: 'Dom',
    defaultOrder: 96,
    description: 'Zaplanować wspólne posiłki, spacer, czas wolny, odpoczynek',
    createdAt: new Date().toISOString(),
    archivedAt: null,
  },
];
export const INITIAL_SHOPPING_ITEMS: ShoppingItem[] = [];
export const INITIAL_EXPENSES: Expense[] = [];

export const INITIAL_WOOD_INVENTORY: WoodInventory = {
  estimatedM3: 0,
  totalCapacityM3: 15,
  lastCutDate: null,
  logsInBoilerRoom: 0,
  dailyBurnRateWinterM3: 0.1,
  updatedAt: new Date().toISOString(),
};

export const INITIAL_EQUIPMENT: EquipmentItem[] = [];
export const INITIAL_ROOM_SNAPSHOTS: RoomSnapshot[] = [];
export const INITIAL_SOS_ALERTS: SosAlert[] = [];
